### ISSUE TITLE
confusing versions of this code

### ISSUE THREAD

**Issue by grinapo** [theraser/blocksync#1]
Hello,

I am really confused by the various gists and a few repos of this code, but yours seem to have at least commits, so I approach you. :-) 

Have you seen this patch, against the slightly modified original? Supposedly it's fixing some nasty bugs in the original. I cannot really cross-check with your version since it's been heavily modified.
Patch is based on https://gist.github.com/rcoup/1338263#gistcomment-1852411

[diff1.txt](https://github.com/ct16k/blocksync/files/489725/diff1.txt)

**Comment by ct16k** [comment]
The nasty bug is a rounding error when the total size is not a multiple of block size, leaving out the last few bytes. This is fixed in your patch by:

``` python
     size_blocks = size / blocksize
+    if size_blocks * blocksize < size:
+        size_blocks = size_blocks+1
```

while my version uses `math.ceil` (currently [line 284](https://github.com/ct16k/blocksync/blob/master/blocksync.py#L284)):

``` python
 size_blocks = ceil(chunksize / float(blocksize))
```

But thank you for the patch nonetheless, as I've [incorporated](https://github.com/ct16k/blocksync/commit/4438f165f1b78418e6a4d49b1be26f77a01a0a48) some of the other ideas, like the use of posix_fadvise where applicable and configurable hash functions, instead of the hardcoded ones.

By the way, my version is based on [this one](https://gist.github.com/ramcq/0dc76d494598eb09740f), to which I've added functionality I found myself needing.

**Comment by theraser** [comment]
Hello ct16k,

I'm in a small discussion with @rcoup and also invited @JustinAzoff (original Author) - do you want to maintain this script in the future? We should find a central place for it and merge all those gists (if not already happened) to this repo. If you're not interested in hosting it I would offer my account for it. At least I got some ideas (documentation, smaller new features...) for it :)

Best Regards

**Comment by ct16k** [comment]
Since I'm seldomly using it nowadays I don't know if I'd be a good maintainer, as all my testing would be synthetical (as opposed to last year's effort, when I was using the script to recover some VM images form a really broken cluster, so most of the flags I've added got quite some heavy real-world usage).

So if you're willing to host it, then by all means please go ahead; it was never my intention to add to the confusion (which is also why I didn't want to create yet another gist).
